zgrep: with -f SPECIAL, read SPECIAL just once
Problem reported by Fulvio Scapin in: http://bugs.gnu.org/22945
* NEWS: Document this.
* tests/zgrep-f: Add a test.
Adjust a test to cover the case of more than one line in -f's input.
* zgrep.in (with_filename): With -f FILE, if FILE is stdin or not
a regular file, copy it into a temporary and use the temporary.

diff --git a/tests/zgrep-f b/tests/zgrep-f
--- a/tests/zgrep-f
+++ b/tests/zgrep-f
@@ -20,14 +20,22 @@
 
 . "${srcdir=.}/init.sh"; path_prepend_ ..
 
-echo needle > n || framework_failure_
-echo needle > haystack || framework_failure_
+printf 'needle\nn2\n' > n || framework_failure_
+cp n haystack || framework_failure_
 gzip haystack || framework_failure_
 
 fail=0
 zgrep -f - haystack.gz < n > out 2>&1 || fail=1
 
 compare out n || fail=1
+
+if ${BASH_VERSION+:} false; then
+  set +o posix
+  # This failed with gzip 1.6.
+  cat n n >nn || framework_failure_
+  eval 'zgrep -h -f <(cat n) haystack.gz haystack.gz' >out || fail=1
+  compare out nn || fail=1
+fi
 
 # This failed with gzip 1.4.
 echo a-b | zgrep -e - > /dev/null || fail=1
